name: Flutter Build APK

on:
  push:
    branches: [ "flutterflow" ]
  pull_request:
    branches: [ "flutterflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Configurar el entorno de Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Acelera las futuras ejecuciones

      # 2. Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 3. Analizar el código (opcional, detecta errores de sintaxis)
      - name: Analyze project source
        run: flutter analyze --no-fatal-warnings

      # 4. Compilar el APK en modo Release
      # Usamos --no-tree-shake-icons por si usas fuentes de iconos personalizadas de FlutterFlow
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      # 5. Subir el APK como un artefacto de GitHub
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlanNest-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7 # El archivo se guardará por una semana
